install.packages("deSolve")  # installing necessary package for ode functionality 
install.packages("ggplot2")
library(deSolve)
library(ggplot2)

Kmax <-  0.2     # maximal uptake rate for a single cell 
kn <-  0.5  # half saturation constant
n <-  50   # denisty of cells per unit volume

I <-  100    # constant inflow
mu <- 0.6   # outflow 

parms <- list(Kmax = Kmax, kn = kn, n = n, I = I, muc = mu) # list of the above parameters to feed into the ode function

kinetics_chemostat <- function(t, c, parms) {   # nutrient uptake function (takes in time, nutrient [], and constants)
  dcdt <- (parms$I - parms$mu*c + (-((parms$Kmax * c)/(parms$kn + c))*parms$n))  # parms$____ accesses the necessary constant from the parms list
  return(list(dcdt))  # returns the rate of nutrient [] change as a list
}

times <- seq(0, 20, by = 1)  # sequence of times starting from 0-20 by 1 increment 

init_c <- 20  # initial concentration of nutrient to begin with 

output <- ode( y = init_c, func = kinetics_chemostat, times = times, parms = parms)  # calling on the ode function from deSolver to save the solutions of the diff rate equation for each time point

df <- as.data.frame(output) # converting ode output from matrix to data frame for ggplot2

colnames(df) # inspecting colnames to feed into ggplot2 aes parameter

colnames(df)[2] <- "dcdt" # changing ode output col name more meaningfully

plot <- ggplot(df, aes(x = time, y = dcdt)) +   # using ggplot to plot the elements "time" and "dcdt" from the dataframe generated by ode solver
  geom_line(color = "red") + # telling ggplot the graph type
  labs(   # adding labels
    title = ("Nutrient Concentration Rate of Change\nAs a Function of Time"),
    y = ("Nutrient Concentration Rate of Change (dc/dt)"),
    x = ("Time")
  )+
  theme( # adjusting aesthetics 
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey90"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 14, face = "bold"), 
    axis.title.y = element_text(size = 14, face = "bold"), 
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 14, face = "bold")) 



print(plot)
