
# Defining a function that takes two parent chromosomes and returns an offspring using one‑point crossover

# example functionality printed to screen using gene_number of 8
gene_number <- 8         # gene number is number of genes in each chromosome (must be predefined here for my code to work)

# function to create two random parental chromosomes to then use in the function for Question1c
Create_parents <- function(gene_number) {    # This function creates a random set of two parent chromosomes and takes in gene_number as input
  ch1 <- c()
  ch2 <- c()
  
  for(gene_index in 1:gene_number) {      # For each gene in the chromosome 
    if(runif(1) < 0.5) {                   # fill genes with either 0 or 1
      ch1[gene_index] <- 0            # 50% prob of adding 0 or 1
    } else {                        
      ch1[gene_index] <- 1           # append to parent 1 chromosome by gene_index until filled
    }
  }

  for(gene_index in 1:gene_number) {      # restart the for loop to fill parent 2 chromosome in the same way as above
      if(runif(1) < 0.5) {                  
        ch2[gene_index] <- 0           
      } else {                        
        ch2[gene_index] <- 1           
      }
  
    }

  return(list(ch1 = ch1, ch2 = ch2))  # return a list with parent 1 and parent 2 chromosomes
}

# actual function for question1c
offspring <- function(parents_list) {   # function takes in the parents_list generated by the function above
  offspring <- c()  # opens and empty vector for the one offspring produced
  crossover <- sample.int(gene_number, 1) # choose a random crossover point along the chr (in our ex case among 8 genes)
  for(gene_index in 1:gene_number) {   # loop through the gene_index in the total genes
    if(gene_index <= crossover) {     # if the index is less than or equal to the crossover point --> append genes from parent 1 until the index in the offspring vec
      offspring[gene_index] <- parents_list$ch1[gene_index]
    } else {   # if the index is greater than the crossover point, do the same for the rest of the gene_indexes but from parent 2
      offspring[gene_index] <- parents_list$ch2[gene_index]
    }
  }
  return(offspring)  # return the one offspring produced after reproduction and one crossover event
}
  

# to show functionality 
parents_list <- Create_parents(gene_number)  # create two random parental chromosomes
offspring <- offspring(parents_list)  # perform one reproduction event with one point of crossover

# printing result to screen using cat for vectors
cat("The offspring of randomly generated parent 1 and 2 is:" , offspring)

  